"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {Progress} from "@/components/ui/progress";
import {ArrowRightLeft,BookOpen,Copy,LogOut,Play,RefreshCw,ShieldCheck,Trophy,Users} from "lucide-react";

const RES:any={oil:"석유",iron:"철광석",gold:"금",wood:"목재",labor:"노동력"};
const STEPS:any[]=[{name:"농업 사회",tech:"",cost:0,req:{}},{name:"인쇄 공업",tech:"인쇄 기술",cost:30,req:{wood:6,labor:6}},{name:"섬유 공업",tech:"섬유 기술",cost:40,req:{oil:4,labor:8}},{name:"석유 화학",tech:"석유 화학 기술",cost:50,req:{oil:7,gold:1,wood:1,labor:3}},{name:"제철",tech:"제철 기술",cost:60,req:{iron:8,gold:1,labor:3}},{name:"자동차",tech:"자동차 기술",cost:80,req:{oil:2,iron:5,gold:2,labor:3}},{name:"컴퓨터",tech:"컴퓨터 기술",cost:100,req:{oil:1,iron:4,gold:5,labor:2}},{name:"전기·전자 공업",tech:"반도체 기술",cost:200,req:{oil:1,iron:3,gold:6,labor:2}},{name:"첨단 산업",tech:"첨단·미래 기술",cost:300,req:{oil:3,iron:5,gold:2,wood:2,labor:3}}];
type Session={roomCode:string;key:string};type Game={roomCode:string;role:"teacher"|"team";countryId:string|null;state:any;teamCodes?:Record<string,string>;trades:any[]};
function money(n:number){return `${n.toLocaleString("ko-KR")}만원`}

export default function TradeGame(){
 const [session,setSession]=useState<Session|null>(null),[game,setGame]=useState<Game|null>(null),[room,setRoom]=useState(""),[key,setKey]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [offer,setOffer]=useState({buyerId:"",resource:"oil",quantity:1,tradeType:"cash",price:1,receiveResource:"labor",receiveQuantity:1,memo:""}),[fineCountry,setFineCountry]=useState("kr"),[created,setCreated]=useState<any>(null);
 const tell=(m:string)=>{setNotice(m);setTimeout(()=>setNotice(""),2800)};
 const call=useCallback(async(body:any,s=session)=>{if(!s)throw new Error("접속 정보가 없습니다.");const r=await fetch("/api/game",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,roomCode:s.roomCode,key:s.key})}),j=await r.json();if(!r.ok)throw new Error(j.error||"요청에 실패했습니다.");return j},[session]);
 const sync=useCallback(async(s=session,quiet=true)=>{if(!s)return;try{const r=await fetch(`/api/game?room=${s.roomCode}`,{headers:{"x-game-key":s.key},cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error);setGame(j);if(!offer.buyerId&&j.state?.countries){const other=j.state.countries.find((c:any)=>c.id!==j.countryId);if(other)setOffer(v=>({...v,buyerId:other.id}))}}catch(e:any){if(!quiet)tell(e.message)}},[session,offer.buyerId]);
 useEffect(()=>{const raw=localStorage.getItem("trade-room-session");if(raw){const s=JSON.parse(raw);setSession(s);sync(s,false)}},[]);
 useEffect(()=>{if(!session)return;const id=setInterval(()=>sync(session),1500);return()=>clearInterval(id)},[session,sync]);
 async function createRoom(){setBusy(true);try{const r=await fetch("/api/game",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:"create"})}),j=await r.json();if(!r.ok)throw new Error(j.error);const s={roomCode:j.roomCode,key:j.teacherPin};setCreated(j);setSession(s);localStorage.setItem("trade-room-session",JSON.stringify(s));await sync(s,false)}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 async function join(){setBusy(true);try{const s={roomCode:room.trim().toUpperCase(),key:key.trim()};const j=await call({op:"join"},s);setSession(s);setGame(j);localStorage.setItem("trade-room-session",JSON.stringify(s));setCreated(null)}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 async function act(action:any,msg?:string){setBusy(true);try{await call({op:"action",action});await sync(session,false);if(msg)tell(msg)}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 function logout(){localStorage.removeItem("trade-room-session");setSession(null);setGame(null);setCreated(null);setRoom("");setKey("")}
 if(!game)return <main className="entry"><section className="entry-card"><div className="anchor">⚓</div><p className="eyebrow">실시간 교실 무역 게임</p><h1>우리가 무역왕!</h1><p className="lead">계정 없이 방 코드와 모둠 코드로 입장하세요.</p><div className="join-grid"><div className="join-panel teacher"><ShieldCheck/><h2>교사</h2><p>새 게임방을 만들고 6개 모둠을 관리합니다.</p><Button size="lg" onClick={createRoom} disabled={busy}>{busy?"만드는 중…":"새 게임방 만들기"}</Button></div><div className="join-panel"><Users/><h2>모둠 입장</h2><p>선생님이 알려준 두 코드를 입력하세요.</p><label>방 코드<Input value={room} onChange={e=>setRoom(e.target.value.toUpperCase())} maxLength={6} placeholder="예: A7K9Q2"/></label><label>모둠 또는 교사 코드<Input value={key} onChange={e=>setKey(e.target.value)} maxLength={6} inputMode="numeric" placeholder="숫자 코드"/></label><Button size="lg" onClick={join} disabled={busy||room.length<6||key.length<4}>입장하기</Button></div></div></section>{notice&&<div className="notice">{notice}</div>}</main>;
 const countries=game.state.countries,me=game.role==="team"?countries.find((c:any)=>c.id===game.countryId):null,total=countries.reduce((a:number,c:any)=>a+c.stage,0),pending=game.trades.filter(t=>t.status==="pending"),incoming=pending.filter(t=>game.role==="teacher"||t.buyerId===game.countryId),next=me&&STEPS[Math.min(8,me.stage+1)];
 const cname=(id:string)=>countries.find((c:any)=>c.id===id);const copy=(s:string)=>navigator.clipboard.writeText(s).then(()=>tell("복사했습니다."));
 return <div className="app-shell"><header className="game-head"><div className="brand"><span>⚓</span><div><b>우리가 무역왕!</b><small>방 코드 {game.roomCode}</small></div></div><div className="overall"><span>전체 산업 발전도 <b>{total}/48</b></span><Progress value={total/48*100}/></div><div className="live"><i/> 실시간 연결</div><Button variant="ghost" size="icon" onClick={logout} aria-label="나가기"><LogOut/></Button></header>
 <main className="game-main">
 {game.role==="teacher"&&<>
  <section className="teacher-strip"><div><p className="eyebrow">교사 관리 화면</p><h1>6개 모둠의 무역 현황</h1></div><div className="teacher-actions"><Button variant="outline" onClick={()=>act({kind:"reset"},"새 게임을 시작했습니다.")} disabled={busy}><RefreshCw/>초기화</Button><Button onClick={()=>act({kind:"start"},"게임을 시작했습니다.")} disabled={busy||game.state.status==="playing"}><Play/>게임 시작</Button></div></section>
  <section className="access-card"><div><h2><ShieldCheck/> 모둠 접속 코드</h2><p>공용 링크와 해당 국가 코드만 각 모둠에 전달하세요.</p></div><div className="room-code"><span>방 코드</span><button onClick={()=>copy(game.roomCode)}>{game.roomCode}<Copy/></button></div><div className="team-code-grid">{countries.map((c:any)=><button key={c.id} onClick={()=>copy(`${game.roomCode} / ${game.teamCodes?.[c.id]}`)}><span>{c.flag} {c.name}</span><b>{game.teamCodes?.[c.id]}</b><Copy/></button>)}</div></section>
 </>}
 {game.role==="team"&&me&&<section className="team-hero"><div><p className="eyebrow">우리 모둠</p><h1>{me.flag} {me.name}</h1><p>다른 국가는 볼 수 있지만 수정할 수 없습니다.</p></div><div className="stage-orb"><b>{me.stage}</b><span>단계<br/>{STEPS[me.stage].name}</span></div></section>}
 <section><div className="section-title"><h2>국가 현황</h2><span className={`status ${game.state.status}`}>{game.state.status==="waiting"?"시작 대기":game.state.status==="playing"?"게임 진행 중":"게임 종료"}</span></div><div className="country-grid">{countries.map((c:any)=><article key={c.id} className={`country-card ${c.id===game.countryId?"mine":""} ${c.stage===8?"winner":""}`}><div className="country-top"><span>{c.flag}</span><div><h3>{c.name}</h3><b>{money(c.money)}</b></div><strong>{c.stage}</strong></div><Progress value={c.stage/8*100}/><div className="stocks">{Object.entries(RES).map(([k,v])=><div key={k}><span>{v as string}</span><b>{c.r[k]}</b></div>)}</div>{game.role==="teacher"&&<Button variant="outline" size="sm" onClick={()=>{setFineCountry(c.id);act({kind:"fine",countryId:c.id,reason:"규칙 위반"},`${c.name}에 벌금 10만원을 부과했습니다.`)}} disabled={busy}>벌금 10만원</Button>}</article>)}</div></section>
 <section className="play-grid">
  {game.role==="team"&&me&&<div className="work-card"><div className="card-title"><BookOpen/><div><h2>기술·산업 발전</h2><p>{me.stage===8?"첨단 산업을 달성했습니다.":`${me.stage+1}단계 ${next.name}`}</p></div></div>{me.stage<8&&<><div className="tech-line"><div><span>필요 기술</span><b>{next.tech}</b><small>개발 비용 {money(next.cost)}</small></div><span className={me.tech?"done":"todo"}>{me.tech?"구매 완료":"구매 전"}</span></div><div className="req-grid">{Object.entries(next.req).map(([k,v]:any)=><div className={me.r[k]>=v?"enough":"short"} key={k}><span>{RES[k]}</span><b>{me.r[k]} / {v}</b></div>)}</div><Button className="full" onClick={()=>act({kind:me.tech?"develop":"buyTech"},me.tech?"산업 발전에 성공했습니다!":"기술을 구매했습니다.")} disabled={busy||game.state.status!=="playing"}>{me.tech?"산업 발전하기":`${next.tech} 구매`}</Button></>}</div>}
  {game.role==="team"&&me&&<div className="work-card"><div className="card-title"><ArrowRightLeft/><div><h2>거래 제안 보내기</h2><p>상대 모둠이 수락하면 거래가 완료됩니다.</p></div></div><div className="form-grid"><label>구매 국가<NativeSelect value={offer.buyerId} onChange={e=>setOffer({...offer,buyerId:e.target.value})}>{countries.filter((c:any)=>c.id!==me.id).map((c:any)=><NativeSelectOption key={c.id} value={c.id}>{c.flag} {c.name}</NativeSelectOption>)}</NativeSelect></label><label>거래 방식<NativeSelect value={offer.tradeType} onChange={e=>setOffer({...offer,tradeType:e.target.value})}><NativeSelectOption value="cash">현금 거래</NativeSelectOption><NativeSelectOption value="barter">물물교환</NativeSelectOption></NativeSelect></label><label>내가 줄 자원<NativeSelect value={offer.resource} onChange={e=>setOffer({...offer,resource:e.target.value,receiveResource:offer.receiveResource===e.target.value?Object.keys(RES).find(k=>k!==e.target.value)!:offer.receiveResource})}>{Object.entries(RES).map(([k,v])=><NativeSelectOption key={k} value={k}>{v as string}</NativeSelectOption>)}</NativeSelect></label><label>내가 줄 수량<Input type="number" min="1" value={offer.quantity} onChange={e=>setOffer({...offer,quantity:+e.target.value})}/></label>{offer.tradeType==="cash"?<label>받을 금액(1만원 단위)<Input type="number" min="0" step="1" value={offer.price} onChange={e=>setOffer({...offer,price:+e.target.value})}/></label>:<><label>받을 자원<NativeSelect value={offer.receiveResource} onChange={e=>setOffer({...offer,receiveResource:e.target.value})}>{Object.entries(RES).filter(([k])=>k!==offer.resource).map(([k,v])=><NativeSelectOption key={k} value={k}>{v as string}</NativeSelectOption>)}</NativeSelect></label><label>받을 수량<Input type="number" min="1" value={offer.receiveQuantity} onChange={e=>setOffer({...offer,receiveQuantity:+e.target.value})}/></label></>}</div><Input placeholder="메모 (선택)" value={offer.memo} onChange={e=>setOffer({...offer,memo:e.target.value})}/><Button className="full" onClick={()=>act({kind:"offer",...offer},"거래 제안을 보냈습니다.")} disabled={busy||game.state.status!=="playing"}>거래 제안 보내기</Button></div>}
  <div className="work-card"><div className="card-title"><ArrowRightLeft/><div><h2>{game.role==="teacher"?"대기 중인 거래":"받은 거래 제안"}</h2><p>거래가 성립되면 양쪽 장부에 동시에 반영됩니다.</p></div></div><div className="trade-list">{incoming.length===0?<p className="empty">대기 중인 거래가 없습니다.</p>:incoming.map(t=><div className="trade" key={t.id}><div><b>{cname(t.sellerId)?.flag} {cname(t.sellerId)?.name}</b><span> → {cname(t.buyerId)?.flag} {cname(t.buyerId)?.name}</span><p>{RES[t.resource]} {t.quantity}개 ↔ {t.tradeType==="barter"?`${RES[t.receiveResource]} ${t.receiveQuantity}개`:money(t.price)}</p>{t.memo&&<small>{t.memo}</small>}</div><div><Button size="sm" variant="outline" onClick={()=>act({kind:"resolve",tradeId:t.id,decision:"reject"})}>거절</Button><Button size="sm" onClick={()=>act({kind:"resolve",tradeId:t.id,decision:"accept"})}>수락</Button></div></div>)}</div></div>
  <div className="work-card activity"><div className="card-title"><Trophy/><div><h2>최근 활동</h2><p>모든 기기에 자동으로 반영됩니다.</p></div></div>{game.state.logs.slice(0,12).map((l:any,i:number)=><div className="log" key={i}><i/><span>{l.m}</span><time>{new Date(l.t).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}</time></div>)}</div>
 </section></main>{notice&&<div className="notice">{notice}</div>}</div>
}
